### ISSUE TITLE
Private monerod with username & password

### ISSUE THREAD

**Issue by bubonic** [sanderfoobar/feather#1]
Hi-

Simple, clean, and easy to use. Really enjoy this wallet. However, when I input

`username:password@x.x.x.x:port`

Into the manual monerod daemon, upon restart the username and password fields are not remembered. So each time I re-open Feather Wallet, I have to adjust the daemon settings. 

My thought is it's a safe thing not to record those passwords, but maybe they can be hashed into the config file to obfuscate them. 

Just a nuisance having to open my password manager everytime and dig out the password.

**Comment by sanderfoobar** [comment]
Hello, I made this feature back in 2020 and I remember not testing it very well. So it could be that there is something going on with the saving of credentials. In fact, I dislike that whole server/networking choosing logic, it was rushed - because we had a tight deadline.

After Feather's release, the project was transferred to another maintainer. He is hosting the issues over at https://git.featherwallet.org/ (which currently seems to be down). Maybe join `#feather` on OFTC and ask `tobtoht` himself

**Comment by sanderfoobar** [comment]
https://git.featherwallet.org/ seems up again. Kindly create your issue there :)
